#启用端口
server:
  port: 80

#spring boot actuator 监控端点
management:
  endpoint:
    health:
      show-details: always
  endpoints:
    jmx:
      exposure:
        include: '*'
    web:
      exposure:
        include: '*'
  health:
    sentinel:
      enabled: false


spring:
  application:
    #服务名称
    name: spring-cloud-gateway
  cloud:
    #配置网关
    gateway:
      discovery:
        locator:
          enabled: true #启用discoveryClient网关集成，可以实现服务发现
      #配置网关路由转发规则
      routes:
        - id: route1
          uri: lb://nacos-consumer
          predicates:
            - Path=/testOne
            #- After=2022-12-08T14:18:00.000+08:00[Asia/Shanghai]
            #- Before=2022-12-08T14:25:07.569+08:00[Asia/Shanghai]
            #- Between=2022-12-08T14:25:07.569+08:00[Asia/Shanghai], 2022-12-08T14:33:07.569+08:00[Asia/Shanghai]
            #- Cookie=token, 123456
            #- Header=X-Request-Id, \d+
            #- Query=token

        - id: route2
          uri: lb://nacos-provider
          predicates:
            - Path=/test1

          filters:
            - AddRequestHeader=X-Request-red, blue
            - AddRequestParameter=color, lightblue

    nacos:
      server-addr: 121.37.9.58:28848
      discovery:
        username: nacos
        password: nacos

    sentinel:
      transport:
        dashboard: 192.168.30.129:8080
      eager: true
      datasource:
        flow:
          nacos:
            server-addr: 121.37.9.58:28848
            data-id: ${spring.application.name}.json
            group-id: DEFAULT_GROUP
            rule-type: flow
            data-type: json
        degrade:
          nacos:
            server-addr: 121.37.9.58:28848
            data-id: ${spring.application.name}-degrade.json
            group-id: DEFAULT_GROUP
            rule-type: degrade
            data-type: json




