server:
  port: 8083

spring:
  application:
    name: nacos-consumer
  cloud:
    nacos:
      #server-addr: 192.168.30.129:8850,192.168.30.130:8850,192.168.30.131:8850
      server-addr: 121.37.9.58:28848
      discovery:
        username: nacos
        password: nacos

#暴露端点，监控


#增加Hystrix熔断器
feign:
  hystrix:
    enabled: true

